# Generated by Django 6.0 on 2025-12-20 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 20, 14, 13, 14, 218581, tzinfo=datetime.timezone.utc)),
        ),
    ]
