# Generated by Django 5.2.9 on 2025-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_passwordresettoken_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
