# Generated by Django 5.2.9 on 2026-01-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_order_id',
            new_name='order_id',
        ),
    ]
